AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  order-manager

  Sample SAM Template for order-manager
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
 
  # HelloWorldFunctionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: HelloWorldLambdaRole
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: "sts:AssumeRole"
  #     Policies:
  #       - PolicyName: LambdaPolicy
  #         PolicyDocument:
  #           Version: "2012-10-17"
  #           Statement:
  #             # ✅ Allow Lambda to write logs
  #             - Effect: Allow
  #               Action:
  #                 - logs:CreateLogGroup
  #                 - logs:CreateLogStream
  #                 - logs:PutLogEvents
  #               Resource: "*"
  #             # ✅ Allow Lambda to retrieve secrets from AWS Secrets Manager
  #             - Effect: Allow
  #               Action:
  #                 - secretsmanager:GetSecretValue
  #               Resource: "*"
  #               # Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DocumentDBSecret-*
  #             # ✅ FIX: Allow Lambda to create, delete, and describe network interfaces (ENIs)
  #             - Effect: Allow
  #               Action:
  #                 - ec2:CreateNetworkInterface
  #                 - ec2:DescribeNetworkInterfaces
  #                 - ec2:DeleteNetworkInterface
  #                 - ec2:AssignPrivateIpAddresses
  #                 - ec2:UnassignPrivateIpAddresses
  #               Resource: "*"

  #             # ✅ FIX: Allow Lambda to attach network interfaces to itself
  #             - Effect: Allow
  #               Action:
  #                 - ec2:DescribeInstances
  #                 - ec2:ModifyNetworkInterfaceAttribute
  #               Resource: "*"

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.default
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonDynamoDBFullAccess
        - AWSLambdaSQSQueueExecutionRole
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:my-documentdb-*
      # Role: !GetAtt HelloWorldFunctionRole.Arn
      
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
        External:
        - "@aws-sdk/client-secrets-manager"
      

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "IAM Capabilities"
        Parameters:
          - Capabilities
Parameters:
  Capabilities:
    Type: String
    Default: "CAPABILITY_NAMED_IAM"