on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./order-manager
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - run: sam delete --no-confirm-changeset --no-fail-on-empty-changeset
